package dvt.question;

/**
 * Les différentes questions
 * @author Axel Aiello
 * @Date 23/03/2016.
 */
public enum TypeOfQuestion {
    ZEUS1, ZEUS2, ZEUS3, ZEUS4, POSEIDON1, POSEIDON2, POSEIDON3, POSEIDON4, POSEIDON5, SOLDIER1, SOLDIER2, SOLDIER3, SOLDIER4, CUPIDON1, CUPIDON2, CUPIDON3, APHRODITE1, APHRODITE2, APHRODITE3, APPOLON1, APPOLON2, APPOLON3;
}
